#!/usr/bin/env bash

export OS="$(uname -s)"
if [ -z "${1}" ]; then :; else
  export USER="${1}" # overwrite
  if [ "${OS}" = "Darwin" ]; then
    export HOME="/Users/${USER}"
  else
    export HOME="/home/${USER}"
  fi
fi

set -eu

export GITHUB_USERNAME="$(gh api user --jq '.login')"
export SPACER='    '

if [ "${OS}" = "Darwin" ]; then
  export OS_EMOJI=':apple:'
  export INSTALL_BOOTLOADER=""
else
  if [ "${OS}" = "Linux" ]; then
    export OS_EMOJI=':penguin:'
    export INSTALL_BOOTLOADER="--install-bootloader"
  else
    echo 'Unrecognized OS! Got "'"${OS}"'" but expected either "Darwin" or "Linux"'
    exit 1
  fi
fi

export COMMIT_PREFIX='`'"$(date '+%Y/%m/%d %H:%M:%S')"'`'"${SPACER}${OS_EMOJI}"

# Find the configuration directory:
if [ -d "${HOME}/.config/nix" ]; then
  export CONFIG_DIR="${HOME}/.config/nix"
else
  if [ -d /etc/nixos ]; then
    export CONFIG_DIR='/etc/nixos'
  else
    echo "Neither ${HOME}/.config/nix nor /etc/nixos exist!"
    exit 1
  fi
fi

# Synchronize Logseq notes:
if [ "${GITHUB_USERNAME}" = "wrsturgeon" ]; then
  if [ -d "${HOME}/Desktop/logseq/.git" ]; then
    cd "${HOME}/Desktop/logseq"
    git pull || :
    git submodule update --init --recursive --remote || :
    make .updated
    git add -A || :
    git commit -m "${COMMIT_PREFIX}" || :
    git push || :
  fi
fi

# Nav to the configuration directory:
cd "${CONFIG_DIR}"

# git fetch --all
# if [ "${GITHUB_USERNAME}" = "wrsturgeon" ]; then
  git pull || :
# else
#   git reset --hard origin/main
# fi

nixfmt .

# Check if anything changed, and, if so, remove the success/failure flag:
if [ -z "$(git status --porcelain)" ]; then :; else
  rm -f .build-succeeded .build-failed
fi

# Push changes upstream with a W.I.P. note (wrench emoji):
if [ "${GITHUB_USERNAME}" = "wrsturgeon" ]; then
  if [ -f .build-succeeded ]; then :; else
    if [ -f .build-failed ]; then :; else
      git add -A || :
      git commit -m "${COMMIT_PREFIX}${SPACER}:wrench:${SPACER}${USER}" || :
      git push || :
    fi
  fi
fi

# Update dependencies:
nix flake update || : # rate limits!
if [ -z "$(git status --porcelain)" ]; then :; else
  if [ "${GITHUB_USERNAME}" = "wrsturgeon" ]; then
    git add -A
    git commit -m "${COMMIT_PREFIX}${SPACER}:arrow_up:${SPACER}${USER}" || :
    git push || :
  fi
fi

if [[ "${OS}" == "Linux" ]]; then
  cd /etc/nixos
  sudo -A git fetch
  sudo -A git reset --hard origin/main
  export CMD="sudo -A nixos-rebuild"
else
  if [[ "${OS}" == "Darwin" ]]; then
    if command -v 'darwin-rebuild' &> /dev/null; then
      export CMD='darwin-rebuild'
    else
      export CMD="nix --extra-experimental-features flakes --extra-experimental-features nix-command run nix-darwin --"
    fi
    if [ -f /etc/nix/nix.conf ]; then
      if [ -z "$(grep '^sandbox = true' /etc/nix/nix.conf)" ]; then :; else
        rm -f ./nix-conf
        sudo cp /etc/nix/nix.conf ./nix-conf
        sed -i '' 's/^sandbox = true/sandbox = false/g' ./nix-conf
        sudo mv ./nix-conf /etc/nix/nix.conf
      fi
    fi
  else
    echo 'Unrecognized OS'
    exit 1
  fi
fi

# Rebuild the Nix system:
if
  ${CMD} switch --flake "${CONFIG_DIR}" --keep-going -v -j auto --show-trace ${INSTALL_BOOTLOADER}
then
  cd "${CONFIG_DIR}"
  rm -f .build-succeeded .build-failed
  touch .build-succeeded
  if [ "${GITHUB_USERNAME}" = "wrsturgeon" ]; then
    git add .build-succeeded || :
    git add .build-failed || :
    git commit -m "${COMMIT_PREFIX}${SPACER}:white_check_mark:${SPACER}${USER}" || :
    git push || :
  fi
else
  cd "${CONFIG_DIR}"
  rm -f .build-succeeded .build-failed
  touch .build-failed
  if [ "${GITHUB_USERNAME}" = "wrsturgeon" ]; then
    git add .build-succeeded || :
    git add .build-failed || :
    git commit -m "${COMMIT_PREFIX}${SPACER}:fire:${SPACER}${USER}" || :
    git push || :
  fi
  exit 1
fi

gh api user --jq '.login' &> /dev/null || gh auth login
sudo -i gh api user --jq '.login' &> /dev/null || sudo -i gh auth login

# Delete all old `result` symlinks from `nix build`s:
nix-store --gc --print-roots | grep 'result -> ' | sed -n -e 's/ -> .*$//p' | xargs rm
nix-store --gc --print-roots | grep '\/\.direnv' | sed -n -e 's/.direnv.*$/.direnv/p' | xargs rm -fr

# From <https://nixos.wiki/wiki/Cleaning_the_nix_store>:
nix-store --gc --print-roots | grep -E -v "^(/nix/var|/run/\w+-system|\{memory|/proc)" | sed -n -e 's/ -> .*$//p' | grep -v '^{censored}$' | xargs rm

# Garbage collection:
nix-collect-garbage --delete-older-than 1d --verbose

# Store optimization:
nix-store --optimise --verbose
