" significant portions taken from <https://www.mojotech.com/blog/vimrc-tutorial/>

" disable `vi` compatibility
set nocompatible

" backspace behavior
set backspace=indent,eol,start

" leader to space
" let mapleader = "\<Space>"

" enable rich color
set t_Co=256

" SHOW TRAILING WHITESPACE WOOHOO
set list
set listchars=tab:>-,trail:.,extends:#,nbsp:.

" command history & undo history
set undolevels=100

" indenting
set softtabstop=2
set shiftround
set smarttab
set autoindent
set nowrap " controversial

" do not fold (hide) regions of code
set nofoldenable

" ruler at column limit
set ruler
" set colorcolumn=100 " imo better than 80

" syntax highlighting
syntax on
filetype on
filetype plugin on
filetype indent on

" search behavior
set incsearch " match as you type

" keep 2 lines above/below the cursor when scrolling
set scrolloff=8
set sidescrolloff=8

" shut the fuck up
" set visualbell " OUCH
set noerrorbells
set belloff=all

" detect non-Vim file changes & read them into the buffer
set autoread

" status bar
set laststatus=2
set showmode
set showcmd

" rendering
set ttyfast

" autocompletion
set wildmenu
set wildmode=list:longest

" update more often
" set updatetime=250

set cot+=preview

" <https://stackoverflow.com/questions/6488683/how-to-change-the-cursor-between-normal-and-insert-modes-in-vim>
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
" reset the cursor on start (for older versions of vim, usually not required)
augroup myCmds
au!
autocmd VimEnter * silent !echo -ne "\e[2 q"
augroup END
