vim.opt.clipboard = 'unnamedplus' -- system clipboard
vim.opt.completeopt = {'menu', 'menuone', 'noselect'} -- completion?
vim.opt.cursorline = true
vim.opt.expandtab = true
vim.opt.hlsearch = false
vim.opt.ignorecase = true -- but... (see smartcase)
vim.opt.incsearch = true -- show search results while typing
vim.opt.mouse = nil -- disable mouse input
vim.opt.number = true -- line numbers
vim.opt.relativenumber = false
vim.opt.shiftwidth = 4
vim.opt.showmode = true
vim.opt.smartcase = true
vim.opt.softtabstop = 4
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.tabstop = 4
